package com.retailer.retailer_reward_program_Service.constants;

public class ApplicationConstants {
	
	public String CREATED_SUCCESSFULLY = "CREATED_SUCCESSFULLY";
	public String CUSTOMER_EXIST = "CUSTOMER_EXIST";
	public String CUSTOMER_NOT_EXIST  = "CUSTOMER_NOT_EXIST";
	public String TRANSACTION_ADDED = "TRANSACTION_ADDED";
	public String MONTH_DIFFERENCE_ONE = "MONTH_DIFFERENCE_ONE";
	public String PURCHASE_AMOUNT_MORE= "PURCHASE_AMOUNT_MORE";
	public String PURCHASE_AMOUNT_LESS = "PURCHASE_AMOUNT_LESS";
	public String REWARD_POINTS_MAX = "REWARD_POINTS_MAX";
	public String REWARD_POINTS_MIN = "REWARD_POINTS_MIN";
	public String REWARD_POINTS_ADDED = "REWARD_POINTS_ADDED";
	public String INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";
	public String DELETE_CUSTOMER_TRANSACTION = "DELETE_CUSTOMER_TRANSACTION";

}
